ifdef::env-github,env-browser[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
:outfilesuffix: .adoc
endif::[]

== Advanced Topics

=== Debugging

If you are struggling with running your Arquillian test and you need more info about what is going on underneath, then you can specify `-Darquillian.debug=true`. Arquillian will print out its lifecycle so you will know exactly where it got stuck.
The output has four types of information - you can distinguish them by their prefix:

* (E) Arquillian event that was fired
* (I) Arquillian interceptor that observed the related event context
* (O) Arquillian observer that observed the related event
* (X) Arquillian extension that was registered


=== Test Observer

In case you need to observe one or more Arquillian events and you don't want to deal with the whole SPI machinery, you can use the annotation `@Observer` at your test class and observe any Arquillian event in the context of the related test class (starting with `BeforeClass` and ending with `AfterClass`):

[source,java]
----
@RunWith(Arquillian.class)
@Observer(MyObserver.class)
public class MyTestCase {
----

The Arquillian observer class has to have a non-parametric constructor and the the observer method you can define by `@Observes` annotation:

[source,java]
----
public void observeBeforeClass(@Observes BeforeClass event) {
    ...
}
----
