ifdef::env-github,env-browser[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
:outfilesuffix: .adoc
endif::[]

=== Build Integration
:icons: font


Just because the Arquillian project uses Maven doesn't mean you have to
use it to run your Arquillian tests. Arquillian is designed to have
seamless integration with JUnit and TestNG without any necessary test
framework configuration. That means you can use any build system that
has a JUnit or TestNG task to execute your Arquillian test cases. Since
most of this guide focuses on using Arquillian in a <<maven, Maven>> build, this
chapter is going to be about alternative build systems, namely <<gradle, Gradle>>
and <<ant, Ant>>.

==== Active Build Ingredient

The secret ingredient required to activate the Arquillian test runner is
getting the correct libraries on the classpath. (Often easier said than
done). The libraries consist of the Arquillian container integration and
the container runtime (for an embedded container) or deployment client
(for a remote container).

In general, the steps to incorporate Arquillian into a build, regardless
of what build tool you are using, can be summarized as:

1.  Activate/configure the JUnit or TestNG task/plugin
2.  Add the Arquillian container integration to the test classpath
(e.g.,
org.jboss.arquillian.container:arquillian-%VENDOR%-%TYPE%-%VERSION%)
3.  Add the container runtime (embedded) or deployment client (remote)
to the classpath
4.  Execute the test build task/goal

If you are only running the Arquillian tests on a single container, this
setup is exceptionally straightforward. The challenge comes when you
want to run the tests on multiple containers. It's really just a matter
of putting the correct libraries on the test classpath, though.

For some build systems, isolating multiple classpath definitions is more
tricky than others. For instance, in Maven, you only get one test
classpath per run (without using really advanced plugin configuration).
You can toggle between different test classpath pairings through the use
of profiles. Each profile contains the libraries for a single target
container (a combination of the libraries itemized in steps 2 and 3
above). You'll see this strategy used in the Arquillian examples.

Other build tools, such as Gradle, can easily define new test tasks that
each have their own, unique classpath. This makes it not only possible
to separate out the target containers, but also run the tests against
each one in the same build execution. We'll see an example of that later
in this chapter. Gradle can also emulate the Maven profile strategy
through the use of build fragment imports. We'll also show an example of
that approach for contrast.

[[maven]]
==== Maven

The community has gravitated towards Maven as the preferred build tool
for projects that use Arquillian. Details on how to setup Arquillian in
a Maven project is covered in detail in the
https://arquillian.org/guides/[Arquillian Guides].

[[gradle]]
==== Gradle

https://gradle.org[Gradle] is a build tool that allows you to create
declarative, maintainable, concise and highly-performing builds. More
importantly, in this context, Gradle gives you all the freedom you need
instead of imposing a rigid build lifecycle on you. You'll get a glimpse
of just how flexible Gradle can be by learning how to integrate
Arquillian into a Gradle build.

We'll be contrasting two strategies for running Arquillian tests from
Gradle:

1.  Container-specific test tasks
2.  Test "profiles" via a project property

The first strategy is the recommended one since it gives you the benefit
of being able to run your tests on multiple containers in the same
build. However, the second approach is less esoteric and will be more
familiar to Maven users. Of course, Gradle is so flexible that there are
likely other solutions for this problem. We invite you to give us
feedback if you find a better way (or another way worth documenting).

NOTE: The examples below use the Groovy DSL (`build.gradle`) and assume a
reasonably recent Gradle version. Container adapters are released
independently of Arquillian Core, so substitute the adapter coordinates
and versions that match the container you are targeting.

Let's get the common build stuff out of the way, then dive into the two
strategies listed above.

===== The common build

The simplest Gradle build for a Java project is a sparse few lines.

[source,groovy]
----
plugins {
    id 'java'
}

repositories {
    mavenCentral()
}
----

Put this into a file named build.gradle at the root of the project,
which is the standard location of the Gradle build file. Arquillian and
the common container adapters are all published to Maven Central, so no
extra repository declarations are needed.

We recommend centralizing version numbers at the top of your build to
make upgrading your dependencies easy. Better still, let the Arquillian
BOM manage them for you:

[source,groovy]
----
ext {
    // substitute the current releases
    arquillianVersion = '<arquillian.version>'
    junitVersion = '<junit.version>'
    jakartaeeVersion = '<jakartaee.version>'
    weldAdapterVersion = '<weld.adapter.version>'
    weldVersion = '<weld.version>'
    wildflyArquillianVersion = '<wildfly.arquillian.version>'
}

dependencies {
    testImplementation platform("org.jboss.arquillian:arquillian-bom:${arquillianVersion}")
    testImplementation platform("org.junit:junit-bom:${junitVersion}")

    testImplementation 'org.jboss.arquillian.junit5:arquillian-junit5-container'
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}
----

Both BOMs are imported with `platform(...)`, so the individual Arquillian
and JUnit dependencies below are declared without a version.

TIP: Use `org.jboss.arquillian.junit:arquillian-junit-container` instead if
your tests are written against JUnit 4, or
`org.jboss.arquillian.testng:arquillian-testng-container` for TestNG.
Testing on a Jakarta EE 9+ container? Import
`org.jboss.arquillian.jakarta:arquillian-jakarta-bom` and use the
`org.jboss.arquillian.jakarta` artifacts instead.

In this example, we'll assume the project is compiling against APIs that
are provided by the target container runtime. Gradle has a built-in
`compileOnly` configuration for exactly that — libraries on the compile
classpath but excluded from the runtime classpath:

[source,groovy]
----
dependencies {
    compileOnly "jakarta.platform:jakarta.jakartaee-api:${jakartaeeVersion}"
}
----

Now that the foundation of a build is in place (or you've added these
elements to your existing Gradle build), we are ready to configure the
container-specific test tasks. In the first approach, we'll create a
unique dependency configuration and task for each container.

[[strategy-container-specific-test-tasks]]
===== Strategy #1: Container-Specific Test Tasks

Each project in Gradle is made up of one or more tasks. A task
represents some atomic piece of work which a build performs. Examples
include compiling classes, __executing tests__, creating a JAR,
publishing an artifact to a repository. We are interested in the
executing tests task. But it's not necessarily just a single test task.
Gradle allows you to define any number of test tasks, each having its
own classpath configuration. We'll use this to configure test executions
for each container.

Let's assume that we want to run the tests against two
Arquillian-supported containers, a managed WildFly and Weld SE. We'll
need two components for each container:

1.  A dependency configuration extending the test runtime classpath
2.  A test task using that configuration

We'll start with the Weld SE container. Starting from the Gradle build
defined in the previous section, we first define a configuration for the
test runtime dependencies.

[source,groovy]
----
configurations {
    weldTestRuntime.extendsFrom testRuntimeClasspath
    wildflyTestRuntime.extendsFrom testRuntimeClasspath
}
----

Next we add the container adapter and container runtime for each:

[source,groovy]
----
dependencies {
    weldTestRuntime "org.jboss.arquillian.container:arquillian-weld-embedded:${weldAdapterVersion}"
    weldTestRuntime "org.jboss.weld.se:weld-se-core:${weldVersion}"

    wildflyTestRuntime "org.wildfly.arquillian:wildfly-arquillian-container-managed:${wildflyArquillianVersion}"
}
----

Finally, we define a test task per container:

[source,groovy]
----
tasks.register('weldTest', Test) {
    testClassesDirs = sourceSets.test.output.classesDirs
    classpath = sourceSets.test.output + sourceSets.main.output + configurations.weldTestRuntime
    useJUnitPlatform()
}

tasks.register('wildflyTest', Test) {
    testClassesDirs = sourceSets.test.output.classesDirs
    classpath = sourceSets.test.output + sourceSets.main.output + configurations.wildflyTestRuntime
    useJUnitPlatform()
    systemProperty 'jboss.home', "${buildDir}/wildfly"
}
----

You run a task as follows:

[source,console]
----
gradle weldTest
----

Or, using Gradle's abbreviated task names:

[source,console]
----
gradle wT
----

Since you are creating custom test tasks, you likely want to configure
the default `test` task to either exclude Arquillian tests or to use a
default container.

It's now possible to run the Arquillian tests against both containers in
sequence using a single Gradle command:

[source,console]
----
gradle weldTest wildflyTest
----

Pretty cool, huh?

Now let's look at another way to solve this problem.

[[strategy-test-profiles]]
===== Strategy #2: Test Profiles

Another way to approach integrating Arquillian into a Gradle build is to
emulate the behavior of Maven profiles. In this case, we won't be adding
any extra tasks, rather overriding the configuration of the test task
provided by the Java plugin.

A Maven profile effectively overrides portions of the build
configuration and is activated using a command option (or some other
profile activation setting). In Gradle, a project property passed with
`-P` serves the same purpose.

We then create a partial Gradle build file for each container that
contains the container-specific dependencies and configuration. Create a
file named weld-profile.gradle:

[source,groovy]
----
dependencies {
    testRuntimeOnly "org.jboss.arquillian.container:arquillian-weld-embedded:${weldAdapterVersion}"
    testRuntimeOnly "org.jboss.weld.se:weld-se-core:${weldVersion}"
}
----

And one for WildFly, named wildfly-profile.gradle:

[source,groovy]
----
dependencies {
    testRuntimeOnly "org.wildfly.arquillian:wildfly-arquillian-container-managed:${wildflyArquillianVersion}"
}

test {
    systemProperty 'jboss.home', "${buildDir}/wildfly"
}
----

Now we import the appropriate partial Gradle build into the main build.
The file is selected based on the value of the project property named
`profile`:

[source,groovy]
----
apply from: "${profile}-profile.gradle"
----

Tests are run in the Weld SE runtime using this command:

[source,console]
----
gradle test -Pprofile=weld
----

That's pretty much the same experience you get when you use Maven (and a
whole heck of a lot simpler).

While the configuration is much simpler using the profiles strategy,
there are two things to keep in mind:

1.  It crosses over into more than one build file
2.  You cannot run the tests in each container in a single build
execution

If you have a better idea of how to integrate an Arquillian test suite
into a Gradle build, we'd love to hear it on the
https://github.com/orgs/arquillian/discussions[Arquillian discussion forums].

[[ant]]
==== Ant

Arquillian has no Ant-specific integration, and needs none: the
`<junit>`, `<junitlauncher>` and `<testng>` tasks all accept an
arbitrary classpath, which is the only thing Arquillian requires.

The approach is the same as for any other build tool — resolve the
Arquillian container integration, the container runtime or deployment
client and your test framework onto a path, then hand that path to the
test task. Since Arquillian is distributed via Maven Central, the
simplest way to resolve those artifacts is with
https://ant.apache.org/ivy/[Apache Ivy] or the
https://maven.apache.org/resolver-ant-tasks/[Maven Artifact Resolver Ant
Tasks], rather than by managing jars by hand.

Sketching the JUnit Jupiter case:

[source,xml]
----
<path id="arquillian.test.path">
    <fileset dir="lib/test" includes="**/*.jar"/>
    <pathelement location="${build.classes.dir}"/>
    <pathelement location="${build.test.classes.dir}"/>
    <!-- arquillian.xml and other test resources -->
    <pathelement location="${test.resources.dir}"/>
</path>

<junitlauncher haltOnFailure="true">
    <classpath refid="arquillian.test.path"/>
    <testclasses outputdir="${build.test.reports.dir}">
        <fileset dir="${build.test.classes.dir}" includes="**/*TestCase.class"/>
    </testclasses>
</junitlauncher>
----

Swapping the target container is a matter of pointing `lib/test` (or the
resolved Ivy configuration) at a different container adapter, exactly as
a Maven profile or a Gradle configuration would.
