# This workflow will build a package using Maven and then publish it to the JBoss Nexus snapshot repository
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven JBoss Snapshot Package

on:
  workflow_dispatch:
    inputs:
      jboss_user:
        description: 'JBoss Nexus Repo Username'
        required: true
      jboss_password:
        description: 'JBoss Nexus Repo Password'
        required: true


env:
  JBOSS_ACTOR: ${{ github.event.inputs.jboss_user }}
  JBOSS_PASSWORD: ${{ github.event.inputs.jboss_password }}

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: jboss-snapshots-repository # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Publish to JBoss Nexus Maven Snapshot Repo
      run: mvn -s .github/settings.xml deploy -Prelease -DskipItTests=true
      
